### ISSUE TITLE
PTC heater repair

### ISSUE THREAD

**Issue by fermulator** [dalathegreat/Nissan-LEAF-PTC-heater-reverse-engineering#1]
hi!

first off impressive work you are doing (just stumbled over your content and github)

I’m the OG poster of this thread

https://mynissanleaf.com/viewtopic.php?t=28105

still have the 2015 ptc heater that was failed -
https://www.ebay.ca/itm/266247434541

it /looks/ in mint condition but i have no way to diagnose it

any recommendations for what to do with it?

i am /very/ curious if it was actually failed or not (ie dealership in Canada forced us to purchase replacement unit without confirming it was the problem) - so it could be fully functional!

or maybe “for parts” it could be useful?

**Comment by dalathegreat** [comment]
@fermulator Any 2013+ PTC heater is way different to the ones listed in this repository. These newer style just heat the air, instead of heating coolant that is passed into a loop. The air-heating ones are considered to be much more reliable. Good luch with any further dissecting!

**Comment by fermulator** [comment]
ah fair nuff OK thanks!
